print("Getting to know you!")
yourName = input("What is your name?")
yourFavFood = input("What is your favorite food?")
yourFavMusic = input("What is your favorite music?")
yourDomicile = input("Where do you live?")
print("You are")
print(yourName)
print("You're probably hungry for")
print(yourFavFood)
print("and you're definitely getting your groove on to")
print(yourFavMusic)
print("living in the amazing")
print(yourDomicile)